title: GitHubPages can change the world
author: EABrown3
email: EABrown@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Learning new skills can change the world. GitHubPages are a new skill.
  

# social links
twitter_username: EABrown_daily
github_username:  EABrown3

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
